SELECT p.PERSONAL_ID, p.CURRENT_FIRST_NAME, p.CURRENT_LAST_NAME, p.CURRENT_MIDDLE_NAME, p.CURRENT_PHONE_NUMBER, p.CURRENT_PERSONAL_EMAIL, p.CURRENT_GENDER, b.PLAN_NAME 
FROM PERSONAL p 
JOIN BENEFIT_PLANS b 
ON p.BENEFIT_PLAN_ID = b.BENEFIT_PLANS_ID;

SELECT * FROM PERSONAL
JOIN BENEFIT_PLANS 
ON PERSONAL.BENEFIT_PLAN_ID = BENEFIT_PLANS.BENEFIT_PLANS_ID;