CREATE DATABASE DB_Quanlysinhvien;
use DB_Quanlysinhvien;

CREATE TABLE LOP (
	MALOP VARCHAR(10) NOT NULL,
	TENLOP NVARCHAR(50) NOT NULL,
	SISO INT NOT NULL
	CONSTRAINT pk_MALOP PRIMARY KEY (MALOP)
);

CREATE TABLE SINHVIEN (
	MASV VARCHAR(10) NOT NULL,
	HOLOT NVARCHAR(50) NOT NULL,
	TENSV NVARCHAR(50) NOT NULL,
	SDT VARCHAR(10) NOT NULL,
	MALOP VARCHAR(10) NOT NULL,
	CONSTRAINT pk_MASV PRIMARY KEY (MASV),
	CONSTRAINT fk_MALOP FOREIGN KEY(MASV) REFERENCES LOP(MALOP),
);


INSERT INTO LOP
VALUES ('L1','IS401',0),
	   ('L2','CS201',0),
	   ('L3','IS301',0);
SELECT * FROM LOP;
SELECT * FROM SINHVIEN;

CREATE TRIGGER TR_NHAPDL
ON SINHVIEN
FOR INSERT
AS
BEGIN
    DECLARE @MALOP VARCHAR(10);
    DECLARE @SOSV INT;

	SELECT @SOSV = SISO, @MALOP = LOP.MALOP
	FROM LOP, INSERTED
	WHERE LOP.MALOP = INSERTED.MALOP

    IF @SOSV > 20
    BEGIN
        ROLLBACK TRANSACTION;
        RAISERROR (N'SỐ LƯỢNG ĐÃ QUÁ 20', 16, 1);
    END
    ELSE
    BEGIN
        UPDATE LOP
        SET SISO = @SOSV + 1
        WHERE MALOP = @MALOP;
    END
END;


GO
ALTER TRIGGER TR_DELETE_LOP
ON LOP
FOR DELETE
AS

BEGIN
    IF EXISTS (SELECT * 
		FROM SINHVIEN, DELETED	
		WHERE SINHVIEN.MALOP = DELETED.MALOP)
    BEGIN
        ROLLBACK TRANSACTION;
        RAISERROR (N'KHÔNG THỂ XÓA LỚP NÀY VÌ CÓ SINH VIÊN ĐANG HỌC', 16, 1);
    END
    ELSE
    BEGIN
        PRINT N'XÓA THÀNH CÔNG';
    END
END;

DELETE FROM LOP WHERE MALOP ='L1';

GO
CREATE PROCEDURE INSERTLOP
    @MALOP CHAR(10),
    @TENLOP NVARCHAR(50),
    @SISO INT
AS
	BEGIN
		IF @SISO < 0
			BEGIN
			RAISERROR (N'SỈ SỐ KHÔNG ĐƯỢC BÉ HƠN 0', 16, 1);
			RETURN;
    END
	IF @MALOP IN (SELECT MALOP FROM LOP)
		BEGIN
			RAISERROR (N'TRÙNG MÃ LỚP', 16, 1);
        RETURN;
		END
	ELSE
		INSERT INTO LOP (MALOP, TENLOP, SISO)
		VALUES (@MALOP, @TENLOP, @SISO);
		PRINT N'NHẬP LỚP THÀNH CÔNG';
END;
go
EXEC InsertLOP 'L4', 'hehe','-9'
GO



CREATE TRIGGER TR_UPDATE_MALOP
ON LOP
FOR UPDATE
AS
	BEGIN
		IF UPDATE(MALOP)
			BEGIN
				PRINT N'LỚP NÀY KHÔNG ĐƯỢC SỬA'
				ROLLBACK TRANSACTION
			END
	END;
SELECT * FROM LOP
UPDATE LOP
SET MALOP = 'L2', TENLOP = 'IS404', SISO = 15
WHERE MALOP = 'L3';




