CREATE DATABASE DB_VIDU;
USE DB_VIDU;

CREATE TABLE HOCPHAN(
 MAHP varchar(10) NOT NULL,
 TENHP nvarchar(50) NOT NULL,
 SISO int
 CONSTRAINT pk_MAHP primary key(MAHP),
) Ư

CREATE TABLE DANGKY(
MSSV varchar(10) NOT NULL,
MAHP varchar(10) NOT NULL,
CONSTRAINT fk_MAHP FOREIGN KEY(MAHP) REFERENCES HOCPHAN(MAHP) 
)

SELECT * FROM HOCPHAN;

DECLARE @Siso int
DECLARE @Sisodk int
SELECT @Siso = SISO FROM HOCPHAN
WHERE MAHP = 'IS401';
SELECT @Sisodk = COUNT (*) FROM DANGKY
WHERE MAHP = 'IS401';
IF @Siso > @Sisodk
	Begin 
		INSERT INTO DANGKY VALUES ('S1', 'IS401');
		PRINT N'ĐĂNG KÝ THÀNH CÔNG';
	End
ELSE
	PRINT N'ĐĂNG KÝ KHÔNG THÀNH CÔNG';

SELECT * FROM DANGKY;


CREATE TABLE SINHVIEN (
	MASV int NOT NULL,
	HOTEN nvarchar(40) NOT NULL
)

INSERT INTO SINHVIEN VALUES(1, 'A'),
(2, 'B'),
(5, 'C'),
(7, 'D');

SELECT * FROM SINHVIEN;


DECLARE @STT int 
SET @STT = 1
WHILE EXISTS(SELECT * FROM SINHVIEN WHERE MASV = @STT)
	SET @STT = @STT + 1;
INSERT INTO SINHVIEN
VALUES (@STT, N'Nguyễn Văn A');

SELECT * FROM SINHVIEN;

CREATE TABLE NHANVIEN(MANV INT NOT NULL PRIMARY KEY,
HOTEN nvarchar(50) NOT NULL, NGAYSINH DATE, GIOITINH nvarchar(10));

INSERT INTO NHANVIEN VALUES 
(1, N'Huỳnh Anh Tuấn', 1945-04-30, N'Nam'),
(2, N'Đinh Viết Nhật Tân', 1940-12-02, N'Nam'),
(3, N'Tăng Ngọc Tuân', 1975-10-31, N'Nam'),
(4, N'Nguyễn Thị Yến Nhi', 1962-06-07, N'Nữ'),
(5, N'Trần Thanh Vũ', 1960-12-12, N'Nam'),
(6, N'Huỳnh Ngọc Đăng Khoa', 1966-04-22, N'Nam');